require('myLuaConf.plugins.tresitter')
require('myLuaConf.plugins.telescope')
require('myLuaConf.plugins.theme')
require('myLuaConf.plugins.whichKey')
require('myLuaConf.plugins.lualine')
require('myLuaConf.plugins.completion')
require('myLuaConf.plugins.ai')
require('myLuaConf.plugins.oil')
require('myLuaConf.plugins.surround')
require('myLuaConf.plugins.git')
--require('myLuaConf.plugins.neotest')
require('myLuaConf.plugins.debug')
require('myLuaConf.plugins.mini')
require('myLuaConf.plugins.leap')
require('myLuaConf.plugins.dotnet')
require('myLuaConf.plugins.camelCaseMotions')

